

# isso faz com que todo novo terminal já nasça dentro de uma sessão do tmux
if [[ $(command -v tmux) ]] && [[ -z $TMUX ]] && [[ $TERM != "screen" ]] && [[ $- == *i* ]]; then
     exec tmux new-session \; choose-tree
fi

# ========== Variáveis de ambiente =================
export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share
export XDG_STATE_HOME=$HOME/.local/state
#
export WINEPREFIX=$HOME/.winevn
export ZSH="$HOME/.oh-my-zsh"
export _JAVA_AWT_WM_NONREPARENTING=1
export BROWSER=google-chrome-stable
export DISABLE_AUTO_UPDATE=true
export VISUAL="nvim --noplugin"
export EDITOR="$VISUAL"
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
export OCAMLRUNPARAM=b # Sempre exibir stack trace
export RLWRAP_HOME=~/.cache/rlwrap ; mkdir -p $RLWRAP_HOME
export FVWM_USERDIR=$HOME/.config/fvwm
export ANSIBLE_NOCOWS=1
#
export CLAUDE_CONFIG_DIR="$XDG_CONFIG_HOME"/claude
export ANSIBLE_HOME="${XDG_CONFIG_HOME}/ansible"
export ANSIBLE_GALAXY_CACHE_DIR="${XDG_CACHE_HOME}/ansible/galaxy_cache"
export ANSIBLE_LOCAL_TEMP="${XDG_CACHE_HOME}/ansible/tmp"
export ANSIBLE_SSH_CONTROL_PATH_DIR="${XDG_CACHE_HOME}/ansible/cp"
export ANSIBLE_ASYNC_DIR="${XDG_CACHE_HOME}/ansible_async"
export GOPATH="$XDG_DATA_HOME"/go
export GOMODCACHE="$XDG_CACHE_HOME"/go/mod
export NPM_CONFIG_USERCONFIG=$XDG_CONFIG_HOME/npm/npmrc
export CARGO_HOME="$XDG_DATA_HOME"/cargo
#
export PATH=$PATH:$HOME/shell/
export PATH=$PATH:$HOME/.local/bin
export PATH=$PATH:$GOPATH/bin/
export PATH=$PATH:$HOME/.npm/bin
# ========== Variáveis de ambiente =================

# Coisas que dependem de uma sessão xorg vem aqui.
if xrandr >/dev/null 2>&1; then 
    xset r rate 250 45 # teclado rate
fi 

# ============== oh-my-zsh ==============
ZSH_THEME="nicoulaj"
COMPLETION_WAITING_DOTS="true"
plugins=(
    # git
    # zsh-autosuggestions
    # zsh-autocomplete
)
source $ZSH/oh-my-zsh.sh
# ============== oh-my-zsh ==============

# ============== Funções ==============
function forkmpvloop {
    for link in "$@"; do
        echo $link
        mpv "$link" --loop=yes &> /dev/null &
    done
}
alias fml="forkmpvloop"

WALKER_SKIP=".PlayOnLinux,.winevn,.wine,.cache,seed,node_modules,venv,.venv,.git,.nix-defexpr,.wine64,CacheStorage,.local,.opam,Downloads,.go,.claude"
#
function fvim {
    WALKER_ROOT=""
    if [[ -z $1 ]]; then
        WALKER_ROOT=$HOME
    else
        WALKER_ROOT=$1
    fi

    FOUND=$(fzf --bind=ctrl-j:accept        \
        --walker-root=$WALKER_ROOT   \
        --multi                      \
        --layout=reverse             \
        --walker-skip="$WALKER_SKIP" \
        --tmux=center                \
        --border=double              \
        --border-label="open in vim" \
        --preview='head -$LINES {}'  \
        --preview-label=preview)
    if [[ -f $FOUND ]]; then
        nvim "$FOUND"
    fi
}
#
function cdf {
    WALKER_ROOT=""
    if [[ -z $1 ]]; then
        WALKER_ROOT=$HOME
    else
        WALKER_ROOT=$1
    fi

    FOUND=$(fzf --bind=ctrl-j:accept \
        --walker="dir,hidden"        \
        --walker-root=$WALKER_ROOT   \
        --multi                      \
        --layout=reverse             \
        --walker-skip="$WALKER_SKIP" \
        --tmux=center                \
        --border=double              \
        --border-label="goto directory" \
        --preview='ls -la {}'  \
        --preview-label=preview)

    if [[ -d $FOUND ]]; then
        echo "cd $FOUND"
        cd "$FOUND"
    fi
}

function y() {
	local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
	command yazi "$@" --cwd-file="$tmp"
	IFS= read -r -d '' cwd < "$tmp"
	[ "$cwd" != "$PWD" ] && [ -d "$cwd" ] && builtin cd -- "$cwd"
	rm -f -- "$tmp"
}
# ============== Funções ==============

# ============== Aliases ==============
alias ls="ls -h -l -p --color=auto --group-directories-first"
alias rm="rm -I"
alias cp="cp -r"
alias la="ls -a"
alias l="ls -lh"
alias du="du --apparent-size"
alias neofetch="neofetch --disable resolution icons host theme"
alias clip="xclip -selection clipboard" 
alias so="source $HOME/.zshrc"
alias df="df -h" 

alias jpwine="LC_ALL=ja_JP.sjis wine" 
alias lt='ls --human-readable --size -1 -S --classify' 
alias logout="pkill -u $USER"
alias ffmpeg="time ffmpeg -hide_banner"
alias ffprobe="ffprobe -hide_banner"
alias rsync="time rsync -vP" 
alias temp='curl "https://wttr.in/?format=3"'
alias ssh="ssh -qXYC"
alias :q="exit"
# alias smartctl="smartctl -a -T permissive"
alias vim="nvim"
alias nsxiv="nsxiv -a"
alias tsxiv="/usr/bin/ls -t | nsxiv -a -o - 2>/dev/null"
alias h2d="printf '%d\n'"
alias d2h="printf '%02x\n'"
alias ocaml="rlwrap ocaml"
# ============== Aliases ==============
