---
- name: install dependencies
  become: true
  when: pacman_install
  community.general.pacman:
    state: present
    name:
      - glibc
      - libx11
      - libxft
      - imlib2
      - fontconfig
      - freetype2
      - glibc
      - libxcb
      - libxrender
      - libxext
      - libx11
      - libxcb
      - expat
      - zlib
      - bzip2
      - libpng
      - brotli
      - libxau
      - libxdmcp
      - brotli

- name: install dependencies
  become: true
  when: apt_install
  ansible.builtin.apt:
    state: present
    name:
      - libx11-dev
      - libimlib2-dev

- name: full
  tags: terminal
  when: make_install
  block:
    - name: clone repo
      ansible.builtin.git:
        repo: https://github.com/silva-guimaraes/st-flexipatch.git
        dest:  "~{{ ansible_user_id }}/.local/share/st-flexipatch"
        update: false
    - name: build
      ansible.builtin.command:
        chdir: "~{{ ansible_user_id }}/.local/share/st-flexipatch"
        cmd: make
    - name: install
      become: true
      ansible.builtin.command:
        chdir: "~{{ ansible_user_id }}/.local/share/st-flexipatch"
        cmd: make install
