---
- name: install dependencies
  become: true
  when: pacman_install
  community.general.pacman:
    state: present
    name:
      - glibc
      - libx11
      - libxft
      - imlib2
      - fontconfig
      - freetype2
      - glibc
      - libxcb
      - libxrender
      - libxext
      - libx11
      - libxcb
      - expat
      - zlib
      - bzip2
      - libpng
      - brotli
      - libxau
      - libxdmcp
      - brotli

- name: full
  tags: terminal
  when: make_install
  block:
    - name: clone repo
      ansible.builtin.git:
        repo: https://github.com/silva-guimaraes/st-flexipatch.git
        dest: /tmp/st-flexipatch
    - name: build
      ansible.builtin.command:
        cmd: make
        chdir: /tmp/st-flexipatch
    - name: install
      become: true
      ansible.builtin.command:
        cmd: make install
        chdir: /tmp/st-flexipatch
