---
- name: full
  tags: terminal
  when: make_install
  block:
    - name: clone repo
      ansible.builtin.git:
        repo: git@github.com:silva-guimaraes/st-flexipatch.git
        dest: /tmp/st-flexipatch
    - name: build
      ansible.builtin.command:
        cmd: make
        chdir: /tmp/st-flexipatch
    - name: install
      become: true
      ansible.builtin.command:
        cmd: make install
        chdir: /tmp/st-flexipatch
