---
- name: main
  hosts: localhost
  vars_files:
    - secrets.yml
  roles:
    - zsh
    - st
    - nvim
    - mpv
    - yazi
    - tmux
    - nsxiv
    - xmodmap
    - nas
    - keepassxc
    - thunderbird
    - strawberry
