---
- name: main
  hosts: localhost
  vars_files:
    - secrets.yml
  roles:
    - { role: zsh,          tags: [zsh, terminal] }
    - { role: st,           tags: [st, terminal] }
    - { role: nvim,         tags: nvim }
    - { role: mpv,          tags: mpv }
    - { role: yazi,         tags: yazi }
    - { role: tmux,         tags: [tmux, terminal] }
    - { role: nsxiv,        tags: nsxiv }
    - { role: x11,          tags: x11 }
    - { role: nas,          tags: nas }
    - { role: keepassxc,    tags: keepassxc }
    - { role: thunderbird,  tags: thunderbird }
    - { role: strawberry,   tags: strawberry }
    - { role: fastfetch,    tags: fastfetch }
