---
- name: pacman install
  become: true
  when: pacman_install
  community.general.pacman:
    state: present
    name:
      - yazi
      - mediainfo
      - ffmpeg

- name: apt full
  become: true
  when: apt_install
  block:
    - name: add apt repo
      ansible.builtin.deb822_repository:
        name: yazi
        components: main
        suites: stable
        signed_by: https://yazi-rs.github.io/builds/yazi-keyring.gpg
        uris: https://yazi-rs.github.io/builds
    - name: apt install
      ansible.builtin.apt:
        update_cache: true
        name:
          - yazi
          - mediainfo
          - ffmpeg
        state: present

- name: symlink config
  ansible.builtin.file:
    src: ~/dotfiles/roles/yazi/files
    path: ~/.config/yazi
    state: link
