---
- name: install
  become: true
  when: pacman_install or apt_install
  ansible.builtin.package:
    state: present
    name:
      - fcitx5
      - fcitx5-mozc

- name: ensure .config/fcitx5
  ansible.builtin.file:
    name: ~/.config/fcitx5
    state: directory

- name: symlink config
  ansible.builtin.file:
    src: "~/dotfiles/roles/fcitx5/files/{{ item }}"
    path: "~/.config/fcitx5/{{ item }}"
    state: link
  loop:
    - profile
    - config
