---
- name: install
  become: true
  when: pacman_install
  community.general.pacman:
    state: present
    name:
      - xclip
      - xorg-xmodmap
      - xorg-xset
    
- name: symlink xmodmap config
  ansible.builtin.file:
    src: ~/dotfiles/roles/x11/files/Xmodmap
    path: ~/.Xmodmap
    state: link

- name: run
  ansible.builtin.command: xmodmap ~/.Xmodmap
