---
- name: install
  become: true
  when: pacman_install
  community.general.pacman:
    state: present
    name:
      - neovim

- name: ensure .config/nvim
  ansible.builtin.file:
    name: ~/.config/nvim
    state: directory

- name: symlink config
  ansible.builtin.file:
    src: "~/dotfiles/roles/nvim/files/{{ item }}"
    path: "~/.config/nvim/{{ item }}"
    state: link
  loop:
    - init.lua
    - lua
